### ISSUE TITLE
Redesign the expenses screen

### ISSUE THREAD

**Issue by mohitkhatri06** [GVR-Secure-Solutions/lekkalu-app#15]

**Comment by bharathkumarchowdary** [comment]
@mohitkhatri06 , can you please decouple the 2 functionalities of this issue into separate issues?
Also what is the need for redesign? And also about how the updated expense page should look/behave like?
Do you have some figma designs ready to share to this issue?

We can discuss and decide whether we need a change

**Comment by mohitkhatri06** [comment]
@bharathkumarchowdary okay i will decouple the issues and yes I have some designs with me.

**Comment by bharathkumarchowdary** [comment]
> @bharathkumarchowdary okay i will decouple the issues and yes I have some designs with me.

Isn't it better to have those designs and the related discussion in this PR?
