### ISSUE TITLE
After post action the income and expense fetch list not showing

### ISSUE THREAD

**Issue by mohitkhatri06** [GVR-Secure-Solutions/lekkalu-app#56]
1. add expense/income in the income statement 
2.  then after successfully 200 status the list is not updating or fetching the new data

**Comment by imhardikdesai** [comment]
@mohitkhatri06 please assign this to me

**Comment by mohitkhatri06** [comment]
https://github.com/GVR-Secure-Solutions/lekkalu-app/pull/61
